### ISSUE TITLE
the muti_key_monitoring data to csv error

### ISSUE THREAD

**Issue by dgnugeek** [zubayr/fetch_monitoring_data_to_csv#1]
Hi Developer, Nice impressive work, however while working on the multi key part, encountered following error..
Traceback (most recent call last):
  File "./fetch_monitoring_data_to_csv.py", line 307, in <module>
    debuglevel=args.debug_level)
TypeError: fetch_multi_key_monitoring_data_to_csv() got multiple values for keyword argument 'debuglevel'

Thanks...

**Comment by zubayr** [comment]
Hi ,
Thank you. There are issue at line 307. 
Have fixed it, can you please check again.

I dont have a Zabbix setup currently, was not able to test it.

Regards,
Zubair AHMED.

**Comment by zubayr** [comment]
Hi,
Just fixed another issue with Zabbix_Api (update it with latest zabbix-api).
Have tested the code as well. should work now.

Regards,
Zubair AHMED.

**Comment by dgnugeek** [comment]
Thank you, just validated the new release and its working ,the changes seem to work. Thanks again.
Regards,

**Comment by zubayr** [comment]
Cool. Will close this Issue then. Cheers.
